version: "3.9"
services:
  app:
    restart: always
    build: .
    environment:
      MYSQL_DATABASE: wdda
      MYSQL_USER: wdda
      MYSQL_PASSWORD: Ohx2gai4AiNaedaegah9boDae8kai9eidahmei1X
      ASPNETCORE_ENVIRONMENT: Production
      VIRTUAL_HOST: wdda.local,afwas.tobiass.nl
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - proxy
      - wdda


  db:
    image: mariadb:10.5.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Oosoo8nai3ahNgo1aidaiQuoobaequ9sae4ONg6a
      MYSQL_DATABASE: wdda
      MYSQL_USER: wdda
      MYSQL_PASSWORD: Ohx2gai4AiNaedaegah9boDae8kai9eidahmei1X
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - wdda

networks:
  wdda:
  proxy:
    external: true
