version: "3.9"
services:
  app:
    restart: always
    build: .
    environment:
      ConnectionStrings__MySql: "Server=db;Database=app;User=app;Password=Ohx2gai4AiNaedaegah9boDae8kai9eidahmei1X;"
      MySqlVersion: 10.5.9
      ASPNETCORE_ENVIRONMENT: Production
      VIRTUAL_HOST: dishmaster.local,dishmaster.tobiass.nl
      LETSENCRYPT_HOST: dishmaster.tobiass.nl
    env_file:
      - .env
    expose:
      - 80
    depends_on:
      - database
    networks:
      - proxy
      - app


  database:
    image: mariadb:10.5.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Oosoo8nai3ahNgo1aidaiQuoobaequ9sae4ONg6a
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: Ohx2gai4AiNaedaegah9boDae8kai9eidahmei1X
    volumes:
      - database:/var/lib/mysql
    networks:
      - app

networks:
  app:
  proxy:
    external: true

volumes:
  database:

