version: "3.9"
services:
  app:
    restart: always
    build: .
    environment:
      ConnectionStrings__MySql: "Server=db;Database=dishmaster;User=dishmaster;Password=Ohx2gai4AiNaedaegah9boDae8kai9eidahmei1X;"
      MySqlVersion: 10.5.9
      ASPNETCORE_ENVIRONMENT: Production
      VIRTUAL_HOST: dishmaster.local,dishmaster.tobiass.nl
      LETSENCRYPT_HOST: dishmaster.tobiass.nl
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - proxy
      - dishmaster


  db:
    image: mariadb:10.5.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Oosoo8nai3ahNgo1aidaiQuoobaequ9sae4ONg6a
      MYSQL_DATABASE: dishmaster
      MYSQL_USER: dishmaster
      MYSQL_PASSWORD: Ohx2gai4AiNaedaegah9boDae8kai9eidahmei1X
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - dishmaster

networks:
  dishmaster:
  proxy:
    external: true
